project:
  type: website
  output-dir: docs
  pre-render: _pre-set-updated.py
  preview:
    port: 4321

website:
  title: "DSAN 5650 Coding Workshop"
  favicon: favicon.png
  repo-url: "https://github.com/jpowerj/dsan5650-workshop"
  repo-actions: [source]
  repo-link-target: "_blank"
  sidebar:
    id: mainnav
    title: "DSAN 5650 Coding Workshop"
    footer: "*Updated {{< env DSAN5650W_LAST_UPDATED \"2025-05-08\" >}}*"
    contents:
      - text: "Workshop Zoom Link <i class='bi bi-box-arrow-up-right ps-1'></i>"
        href: "https://georgetown.zoom.us/j/96955094415?pwd=i68GA6yEySlkaJaaCUTjFQMwuoZ4qt.1"
        target: "_blank"
      - text: "Recordings <i class='bi bi-box-arrow-up-right ps-1'></i>"
        href: "https://georgetown.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=1b54d832-55b1-45df-ad98-b450004b55d5"
        target: "_blank"
      - "---"
      - text: "Week 4: {{< var w04.date-md >}}"
        href: "w04/index.qmd"
      - text: "Week 5: {{< var w05.date-md >}}"
        href: "w05/index.qmd"
      - text: "Week 6: {{< var w06.date-md >}}"
        href: "w06/index.qmd"
      - text: "Week 8: {{< var w08.date-md >}}"
        href: "w08/index.qmd"
      - text: "Week 9: {{< var w09.date-md >}}"
        href: "w09/index.qmd"
      - text: "Week 10: {{< var w10.date-md >}}"
        href: "w10/index.qmd"
      - text: "Week 11: {{< var w11.date-md >}}"
        href: "w11/index.qmd"
      - "---"
      - text: "<i class='bi bi-arrow-left pe-1'></i> Course Homepage"
        href: "https://jjacobs.me/dsan5650"
        target: "_blank"

format:
  html:
    theme:
      light: [default, "./dsan-globals/jjquarto.scss"]
      dark: [darkly, "./dsan-globals/jjquarto.scss"]
    css: "./dsan-globals/jjstyles.css"
    toc: true
    link-external-newwindow: true
    link-external-icon: true
    include-in-header:
      text: "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==' crossorigin='anonymous' referrerpolicy='no-referrer'></script><link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css'><script src='/sidebar.js'></script>"
